# Generated by Django 3.2.15 on 2022-10-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250, unique=True)),
                ('lastname', models.CharField(max_length=250, unique=True)),
                ('mail', models.CharField(max_length=250, unique=True)),
            ],
        ),
    ]
